import clsx from 'clsx'
import { Merriweather } from 'next/font/google'
import Navbar from '@/components/navbar'
import './globals.css'

const font = Merriweather({
  subsets: ['latin'],
  weight: ['400', '700'],
  variable: '--font-merriweather',
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html
      lang="en"
      className={clsx('bg-white text-black dark:bg-[#111010]', font.variable)}
    >
      <body className="mx-auto mb-40 mt-8 flex max-w-3xl flex-col px-4 antialiased md:mt-20 md:flex-row lg:mt-32">
        <Navbar />
        <main className="w-full bg-blue-500">
          {children}
          {/* <Analytics /> */}
        </main>
      </body>
    </html>
  )
}
