import clsx from 'clsx'
import { Merriweather } from 'next/font/google'
import Navbar from '@/components/navbar'
import './globals.css'

const titleFont = Merriweather({
  subsets: ['latin'],
  weight: ['400', '700'],
  variable: '--font-merriweather',
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html
      lang="en"
      className={clsx(
        'bg-white [scrollbar-gutter:stable] text-black dark:bg-[#111010] h-full',
        titleFont.variable
      )}
    >
      <body className="flex flex-col md:flex-row gap-12 mx-auto pt-8 max-w-2xl px-4 antialiased md:pt-20 lg:pt-32 h-full">
        <Navbar />
        <main className="w-full flex flex-col">
          <div className='mb-20'>
            {children}
          </div>
          {/* <Analytics /> */}
          <footer className="text-center pb-4 font-title text-gray-500 text-xs mt-auto">
            Made in 2023
          </footer>
        </main>
      </body>
    </html>
  )
}
