import clsx from 'clsx'
import { Lora, Merriweather } from 'next/font/google'
import Navbar from '@/components/navbar'
import './globals.css'

const titleFont = Merriweather({
  subsets: ['latin'],
  weight: ['400', '700'],
  variable: '--font-merriweather',
})

const mainFont = Lora({
  subsets: ['latin'],
  variable: '--font-lora',
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html
      lang="en"
      className={clsx(
        'bg-white [scrollbar-gutter:stable] text-black dark:bg-[#111010]',
        titleFont.variable,
        mainFont.variable
      )}
    >
      <body className="mx-auto mb-40 mt-8 flex max-w-2xl flex-col gap-12 px-4 antialiased md:mt-20 md:flex-row lg:mt-32">
        <Navbar />
        <main className="w-full">
          {children}
          {/* <Analytics /> */}
        </main>
      </body>
    </html>
  )
}
